package com.practice.springbootKafkaConsumer.data;

/*
 Convenience record with a single-arg constructor so callers can do:
   new WikimediaDTO(eventMessage)
 and let the ID remain null (auto-generated by the entity).
*/
public record WikimediaDTO(Long id, String wikiEventData) {
	public WikimediaDTO(String wikiEventData) {
		this(null, wikiEventData);
	}
}
